
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLFruitsConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLFruits.ModelInput sampleData = new MLFruits.ModelInput()
            {
                ImageSource = @"D:\Source\fruits\images\apples\20220910_101853-0.jpg",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLFruits.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"ImageSource: {@"D:\Source\fruits\images\apples\20220910_101853-0.jpg"}");


            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
